version: '3.7'
services:
    php:
      depends_on:
        - db
      build:
        context: .
        dockerfile: docker/php/Dockerfile
      volumes:
        - './app:/var/www/app'
        - ./docker/logs/php:/var/log

    nginx:
        image: nginx
        restart: always
        ports:
          - 80:80
        volumes:
          - './app:/var/www/app'
          - ./docker/nginx/sites/local.conf:/etc/nginx/conf.d/default.conf
          - ./docker/nginx/local.default.conf:/etc/nginx/local.default.conf
          - ./docker/logs/nginx:/var/log/nginx
#        environment:
#          - NGINX_HOST=test-doc-fast.loc

    db:
      image: mysql:5.7
      ports:
        - '${DB_PORT}:3306'
      command: '--character-set-server=utf8 --collation-server=utf8_general_ci'
      environment:
        MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
        MYSQL_DATABASE: '${MYSQL_DATABASE}'
        MYSQL_USER: '${MYSQL_USER}'
        MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      volumes:
        - './docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
        - './docker/mysql/db_data:/var/lib/mysql'